### PR TITLE
feat: CLIN-3138 Add nextflow test dag

### PR DESCRIPTION
**Pull request by LysianeBouchard**
**Description**

To facilitate team collaboration, this PR introduces generic Nextflow code that can be reused and evolved by the team to implement Nextflow DAGs.

Additionally, we introduce a generic test nextflow DAG that allows launching ad hoc nextflow jobs from the Airflow UI. This feature enables users to test and validate their pipelines in a controlled environment before deploying them to production.

In the short term, we would like to use this DAG for testing an SNV clustering nextflow pipeline. To test with realistic data, it will probably need to run in the staging environment. Please keep this in mind during the review. 

Associated JIRA ticket:
https://ferlab-crsj.atlassian.net/browse/CLIN-3138

**Local tests**

I tested running the nextflow DAG locally with minikube. 

I included documentation about this test procedure in the code. Let me know if you want to keep it or if you prefer that I remove it from this PR.

**Running dag in ETL QA cluster**

I started airflow locally, with docker-compose, and set the `kubernetes_context_etl` variable to point on the etl cluster. I set the `kubernetes_namespace` variable to `cqgc-qa`.  Then I executed the test nextflow dag from the airflow UI.  It was executed successfully. I could see the different pods running on the cluster.

**Slack notifications**

I used the local setup with docker-compose and minikube to execute the nextflow dag. As instructed in the readme, I set the variable `slack_hook_url` to point on a test slack application that I created on a personal slack workspace.
 
The dag was executed successfully and I could see the notifications correctly sent to the test app before and after completing the nextflow job.

Here is a screenshot showing the slack notification sent:
Capture d’écran, le 2024-09-05 à 20 27 56

**Nextflow dag screenshot**

Here is what we see in the UI when we click the trigger button:
Capture d’écran, le 2024-09-05 à 20 39 35

### CODE REVIEW

**Review by jecos — APPROVED** [review]
LGTM

**Comment by LysianeBouchard** [comment]
Added an extra commit to apply corrections. I will squash it before merging. I am not sure that the slack notification works yet. I will keep the draft label until it is tested properly.

**Comment by LysianeBouchard** [comment]
I was able to test the slack notification locally using a test app created on a separated personal workspace. I included a snapshot of the message sent in the PR description.  

I put the templates and .minikube-setup folder with the test documentation under doc/test, as recommended by @creativeyann17 .  I squashed my commits.

Let me know if you have more comments or if there is more tests to run before merging.

**Review by creativeyann17 — APPROVED** [review]

**Comment by LysianeBouchard** [comment]
Thank you both for the review. Merging.

**Pull request merged**
