### PR TITLE
feat: CLIN-3267 align nextflow operator with cqdg k8s operators struc…

### PR DESCRIPTION
**Pull request by LysianeBouchard**
This PR refactor the nextflow operator and associated configuration mechanism to imitate the structure and class hierarchy in cqdg_dags. 

So far, this code has been tested locally with Minikube for test_nextflow_operator. It has not yet been tested on etl.py.
It has also been tested on a dag that is not in this PR (etl_variant_annotation):
https://github.com/Ferlab-Ste-Justine/clin-pipelines-dags/pull/406

**KEY DIFFERENCES WITH CQDG**
This implementation reuses a configuration mechanism similar to CQDG, with the following key differences:

- **2 different k8s contexts**: In this repo, there are 2 different k8s contexts: ETL and DEFAULT. We assume that we will create 2 different instances of KubeConfig, one for each context. So far only the ETL context KubeConfig instance is created.
- **service_account_name specified in BaseConfig instead of KubeConfig**: This is because nextflow and spark operators have different service account names. I thought the intention of the KubeConfig  class is to capture what is always the same and thought that, since it can vary, perhaps it should go in BaseConfig instead. There are other solutions of course. Let me know if you are ok with this one.
- **shallow copy instead deep copy**: In BaseConfig, shallow copy is used instead deep copy in build_operator and partial methods. This is to avoid serializing more complex objects as dictionaries.
- **BaseConfig.args renamed to BaseConfig.append_args**: I suspect that one might think that args overwrite the arguments instead appending, but well this is subjective.

**OTHER CHANGES**
- The nextflow operator supports multiple config maps.
- A few "cosmetic" changes (fix warnings reported by flake8)

**USING DRAFT MODE**

-The etl dag is not tested yet and might be impacted by the changes (through svclustering task group). I would like to make sure that I did everything that is reasonable here.

### CODE REVIEW

**Comment by LysianeBouchard** [comment]
Added a suggestion commit from Laura (git cherry-pick command). I did not squash  the commits together to make Laura's contribution clear. 
I will re-test locally.

**Comment by LysianeBouchard** [comment]
@creativeyann17  I need help to test the etl.py dag. I think that Laura tested directly in QA on her side. I don't know if there is a better way? And if not, is there something special to do in this case?

**Review by laurabegin — APPROVED** [review]

**Comment by laurabegin** [comment]
Une fois les conflits corrigés, moi je suis à l'aise qu'on merge et qu'on teste en QA si c'est aussi ok pour toi @creativeyann17. J'ai testé le minimum possible en local et c'était ok.

**Comment by LysianeBouchard** [comment]
Je faire le rebase ...

**Comment by LysianeBouchard** [comment]
I did the rebase. I tested locally with minikube. The dags are correctly displayed in the UI and I can execute the test_nextflow_operator dag.

**Comment by LysianeBouchard** [comment]
I did more tests with the test_nextflow_operator dag. Found a bug when using non-default parameters. Will fix.

**Comment by LysianeBouchard** [comment]
> I did more tests with the test_nextflow_operator dag. Found a bug when using non-default parameters. Will fix.

Push a fix. You might want to review it.

**Pull request merged**
